# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DeepLinkAndPushNotification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for DeepLinkAndPushNotification
  pod 'PusherSwift'
#  pod 'PushNotifications'
  pod 'OneSignal', '>= 2.5.2', '< 3.0'

end

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for OneSignalNotificationServiceExtension
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
